// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003121517_change")]
    partial class change
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Kẹo",
                            Description = "Các loại kẹo mềm, kẹo cứng, kẹo dẻo nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Socola",
                            Description = "Socola thanh, socola viên và socola hộp nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bánh quy",
                            Description = "Bánh quy bơ, bánh quy socola và bánh quy nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Bánh xốp",
                            Description = "Các loại bánh xốp, wafer và bánh kem xốp"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Snack",
                            Description = "Snack khoai tây, snack ngô và các loại đồ ăn nhẹ"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Bánh ngọt",
                            Description = "Bánh ngọt đóng gói và các loại bánh nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Kẹo dẻo",
                            Description = "Kẹo dẻo trái cây, kẹo dẻo hình thú và kẹo gummy"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Socola cao cấp",
                            Description = "Socola cao cấp, socola quà tặng và socola hộp"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Bánh quy cao cấp",
                            Description = "Bánh quy cao cấp dùng làm quà tặng"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Kẹo bạc hà",
                            Description = "Kẹo bạc hà, kẹo the và kẹo ngậm nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Kẹo trái cây",
                            Description = "Các loại kẹo có hương vị trái cây"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Bánh ăn sáng",
                            Description = "Bánh ngũ cốc, bánh ăn sáng và sản phẩm tiện lợi"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Hạt & Đồ ăn vặt",
                            Description = "Các loại hạt, trái cây sấy và đồ ăn vặt nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Quà tặng bánh kẹo",
                            Description = "Hộp bánh kẹo và set quà tặng Sweet Land"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Bánh kẹo khác",
                            Description = "Các sản phẩm bánh kẹo nhập khẩu khác"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "25 Nguyễn Huệ, Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 1500
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "118 Võ Văn Tần, Quận 3, TP.HCM",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 500
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "72 Nguyễn Trãi, Quận 5, TP.HCM",
                            CustomerName = "Lê Văn Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 100
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "156 Thành Thái, Quận 10, TP.HCM",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905678123",
                            RewardPoints = 2300
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "43 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
                            CustomerName = "Hoàng Văn Đức",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 800
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "89 Phạm Văn Đồng, Quận Gò Vấp, TP.HCM",
                            CustomerName = "Võ Thị Hà",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0987654321",
                            RewardPoints = 3200
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "215 Cộng Hòa, Quận Tân Bình, TP.HCM",
                            CustomerName = "Đặng Văn Giang",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909876543",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "36 Phan Đình Phùng, Quận Phú Nhuận, TP.HCM",
                            CustomerName = "Bùi Thị Hoa",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0913456789",
                            RewardPoints = 1200
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "102 Nguyễn Thị Thập, Quận 7, TP.HCM",
                            CustomerName = "Đỗ Văn Hùng",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0981234567",
                            RewardPoints = 4500
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "68 Hậu Giang, Quận 6, TP.HCM",
                            CustomerName = "Nguyễn Thị Khánh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0903456789",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "145 Võ Văn Ngân, TP. Thủ Đức, TP.HCM",
                            CustomerName = "Trương Văn Long",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0915678901",
                            RewardPoints = 1800
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "234 Lê Văn Khương, Quận 12, TP.HCM",
                            CustomerName = "Phan Thị Mai",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0986789012",
                            RewardPoints = 700
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "57 Lũy Bán Bích, Quận Tân Phú, TP.HCM",
                            CustomerName = "Lý Văn Nam",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0907890123",
                            RewardPoints = 5000
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "321 Tỉnh Lộ 10, Quận Bình Tân, TP.HCM",
                            CustomerName = "Huỳnh Thị Phương",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0918901234",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "78 Nguyễn Hữu Trí, Huyện Bình Chánh, TP.HCM",
                            CustomerName = "Mai Văn Quân",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0989012345",
                            RewardPoints = 2600
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "SWT000001",
                            CategoryId = 7,
                            Price = 95000m,
                            ProductName = "Kẹo dẻo Haribo Goldbears 200g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "SWT000002",
                            CategoryId = 8,
                            Price = 189000m,
                            ProductName = "Socola Ferrero Rocher 16 viên",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "SWT000003",
                            CategoryId = 9,
                            Price = 165000m,
                            ProductName = "Bánh quy bơ Danisa 454g",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "SWT000004",
                            CategoryId = 4,
                            Price = 79000m,
                            ProductName = "Bánh xốp Loacker Quadratini Chocolate 125g",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "SWT000005",
                            CategoryId = 5,
                            Price = 72000m,
                            ProductName = "Snack khoai tây Pringles Original 107g",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "SWT000006",
                            CategoryId = 2,
                            Price = 115000m,
                            ProductName = "Socola KitKat Mini 170g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "SWT000007",
                            CategoryId = 10,
                            Price = 35000m,
                            ProductName = "Kẹo bạc hà Alpenliebe 90g",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "SWT000008",
                            CategoryId = 8,
                            Price = 135000m,
                            ProductName = "Socola Lindt Excellence Dark 100g",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "SWT000009",
                            CategoryId = 3,
                            Price = 45000m,
                            ProductName = "Bánh quy Oreo Original 133g",
                            StockQuantity = 180
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "SWT000010",
                            CategoryId = 11,
                            Price = 69000m,
                            ProductName = "Kẹo trái cây Skittles Fruits 125g",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "SWT000011",
                            CategoryId = 12,
                            Price = 145000m,
                            ProductName = "Bánh ngũ cốc Kellogg's 300g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "SWT000012",
                            CategoryId = 14,
                            Price = 175000m,
                            ProductName = "Hộp quà Socola Merci 250g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "SWT000013",
                            CategoryId = 13,
                            Price = 120000m,
                            ProductName = "Hạt hạnh nhân rang muối 200g",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "SWT000014",
                            CategoryId = 7,
                            Price = 105000m,
                            ProductName = "Kẹo dẻo Trolli Sour Glowworms 200g",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "SWT000015",
                            CategoryId = 3,
                            Price = 125000m,
                            ProductName = "Bánh quy Walkers Shortbread 150g",
                            StockQuantity = 55
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
